# Generated by Django 4.0.5 on 2022-06-10 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tgbot', '0003_rm_unused_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlineServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('api_url', models.CharField(max_length=256)),
                ('cert_sha256', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='OutlineKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('method', models.CharField(max_length=256)),
                ('access_url', models.CharField(max_length=256)),
                ('used_bytes', models.BigIntegerField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vpn.outlineserver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tgbot.user')),
            ],
        ),
    ]
