# Generated by Django 4.0.5 on 2022-06-10 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlinekey',
            name='port',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
